export const DUMMY_RESTAURANTS = [
  {
    id: "1",
    name: "Eni Stores - Nsikak Eduok",
    image: "/eni-stores.jpg",
    rating: 4.5,
    reviews: 1234,
    deliveryTime: "25-30 min",
    location: "Ikot Ekpene Road",
    phone: "08012345678",
    categories: ["All", "Soups", "Snacks", "Rice & Pasta"],
  },
  {
    id: "2",
    name: "Killimanjaro",
    image: "/killimanjaro.jpg",
    rating: 4.3,
    reviews: 856,
    deliveryTime: "20-25 min",
    location: "Ikot Ekpene Road",
    phone: "08098765432",
    categories: ["All", "Grills", "Sides", "Beverages"],
  },
  {
    id: "3",
    name: "Chicken Republic",
    image: "/chicken-republic.jpg",
    rating: 4.7,
    reviews: 2103,
    deliveryTime: "15-20 min",
    location: "Ikot Ekpene Road",
    phone: "08055555555",
    categories: ["All", "Chicken", "Burgers", "Sides"],
  },
]

export const DUMMY_MENU_ITEMS = {
  "1": [
    {
      id: "1-1",
      name: "Okro soup & Garri",
      description: "Thick okro soup with fresh fish, served hot with smooth white garri.",
      price: 2800,
      image: "/okro-soup.jpg",
      category: "Soups",
      ingredients: [
        "Okro",
        "Fresh fish",
        "Palm oil",
        "Crayfish",
        "Stockfish",
        "Periwinkle",
        "Seasoning cubes",
        "Uziza leaves",
        "Pepper",
        "Salt",
      ],
      allergens: "Contains seafood (fish, crayfish, periwinkle) and palm oil.",
    },
    {
      id: "1-2",
      name: "Jellof Rice & Plantain",
      description: "Naija-style jellof rice with crispy, golden plantain slices. Pure comfort food.",
      price: 2200,
      image: "/jellof-rice.jpg",
      category: "Rice & Pasta",
      ingredients: ["Rice", "Tomatoes", "Peppers", "Onions", "Plantain", "Oil", "Seasoning"],
      allergens: "May contain traces of nuts.",
    },
    {
      id: "1-3",
      name: "Shawarma & Coke",
      description: "Spicy beef or chicken shawarma wrapped fresh, served with ice-cold Coke.",
      price: 1500,
      image: "/shawarma.jpg",
      category: "Snacks",
      ingredients: ["Beef/Chicken", "Bread", "Vegetables", "Sauce", "Spices"],
      allergens: "Contains gluten.",
    },
  ],
  "2": [
    {
      id: "2-1",
      name: "Grilled Chicken",
      description: "Perfectly grilled chicken with our special spice blend.",
      price: 3500,
      image: "/grilled-chicken.jpg",
      category: "Grills",
      ingredients: ["Chicken", "Spices", "Herbs"],
      allergens: "None",
    },
    {
      id: "2-2",
      name: "Fried Rice",
      description: "Delicious fried rice with vegetables and protein.",
      price: 2000,
      image: "/fried-rice.png",
      category: "Sides",
      ingredients: ["Rice", "Vegetables", "Eggs", "Oil"],
      allergens: "Contains eggs.",
    },
  ],
  "3": [
    {
      id: "3-1",
      name: "Crispy Fried Chicken",
      description: "Golden, crispy fried chicken pieces.",
      price: 2500,
      image: "/fried-chicken.jpg",
      category: "Chicken",
      ingredients: ["Chicken", "Flour", "Spices"],
      allergens: "Contains gluten.",
    },
    {
      id: "3-2",
      name: "Chicken Burger",
      description: "Juicy chicken burger with fresh toppings.",
      price: 2000,
      image: "/chicken-burger.jpg",
      category: "Burgers",
      ingredients: ["Chicken", "Bread", "Lettuce", "Tomato", "Sauce"],
      allergens: "Contains gluten.",
    },
  ],
}

export const DUMMY_USER = {
  name: "Annie Davies",
  email: "annie.davies@email.com",
  phone: "08012222222",
  avatar: "/user-avatar.jpg",
  address: "Ewet Housing Estate",
  savedAddresses: [
    {
      id: "1",
      label: "Home",
      phone: "08012222222",
      address: "15 Nsikak Eduok, Uyo",
    },
  ],
}

export const DUMMY_DRIVER = {
  name: "Darlington Umoh",
  rating: 3,
  image: "/driver-avatar.jpg",
  phone: "08099999999",
}
